language: java
jdk:
  - oraclejdk8

sudo: false
script:
 - mvn clean install
 - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.m2

notification:
  email:
    - natalia.andrianova@gmail.com